# Shell variables
# Generated by 'wal'
wallpaper='/home/metwas/Pictures/wallpapers/abstract-red-spikes-science-fiction-_2440-37.jpg'

# Special
background='#070707'
foreground='#ed8182'
cursor='#ed8182'

# Colors
color0='#070707'
color1='#423F3F'
color2='#524F50'
color3='#8F0C0D'
color4='#AE0B0B'
color5='#AE2121'
color6='#CE0F0F'
color7='#ed8182'
color8='#a55a5b'
color9='#423F3F'
color10='#524F50'
color11='#8F0C0D'
color12='#AE0B0B'
color13='#AE2121'
color14='#CE0F0F'
color15='#ed8182'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
