#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch alacritty with alt config

CONFIG="$HOME/.config/hypr/alacritty/alacritty.toml"

if [ "$1" == "-f" ]; then
	kitty 
elif [ "$1" == "-F" ]; then
    kitty 
else
	kitty
fi
