#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/metwas/Pictures/wallpapers/abstract-red-spikes-science-fiction-_2440-37.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
